version: "3.8"

name: redis-example
services:
  redis:
    container_name: redis-node
    image: redis:7.0.8
    ports:
      - "6379:6379"
  api:
    restart: on-failure
    build: .
    hostname: api
    ports:
      - "3000:8000"
